name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Construir y subir la imagen de Angular a Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Angular image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest -f ./Dockerfile ./
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest

      # 3. Desplegar en el servidor
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@ ${{ secrets.SERVER_HOST}}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest && \
            docker stop angular-frontend-container || true && \
            docker rm angular-frontend-container || true && \
            docker run -d --name angular-frontend-container -p 81:80 ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest
          "
